proto:
	if [ -d "gen/api/v1" ]; then rm -rf gen/api/v1; fi && mkdir -p ./gen && protoc --go_out=./gen --go-grpc_opt=paths=source_relative --go_opt=paths=source_relative --go-grpc_out=./gen api/v1/*.proto

# if this doesn't work,
# make sure you have installed go, proto and it's related compiler and necessary packages.
# please copy the below command and run it in your terminal manually and then hit "make proto" to generate the stubs
path:
	sudo apt install protobuf-compiler
	go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
	export GOPATH=$HOME/go
	export GOBIN=$GOPATH/bin
	export PATH=$PATH:$GOROOT:$GOBIN
	export PATH="$PATH:$(go env GOPATH)/bin"