################ Build & Dev ################
FROM maven:3.6.3-jdk-8 as build

# Create project directory (workdir)
WORKDIR /app

# Add source code files to WORKDIR
COPY . .

# Set maven build options
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

# Remove old .jar files
RUN rm -f target/*.jar

# Build jar file
RUN mvn package -T 1C -U -Dmaven.test.skip=true

# Rename jar file
RUN cp target/{{.GeneratedJarName}} target/main.jar

################ Production ################
# Creates a minimal image for production using distroless base image
# More info here: https://github.com/GoogleContainerTools/distroless
FROM gcr.io/distroless/java:8 as production

# Copy application binary from build/dev stage to the distroless container
COPY --from=build /app/target/main.jar /

{{if .IsRestServer }}
# Application port (optional)
EXPOSE {{.RestServerPort}}
{{end}}

# Container start command for production
CMD ["/main.jar"]