name: core-release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  push_to_registry:
    name: Build and push Docker image github container registry.
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read
    env:
      REGISTRY: ghcr.io
      GH_URL: https://github.com
    steps:
      - name: Set environment variable
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Test environment variable
        run: echo ${{ env.RELEASE_VERSION }}
      - name: Check out GitHub repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./core
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/core:${{ env.RELEASE_VERSION }}
      - name: Install cosign
        uses: sigstore/cosign-installer@main
      - name: Sign the images
        run: |
          cosign sign -y ${{ env.REGISTRY }}/${{ github.repository }}/core:${{ env.RELEASE_VERSION }}
        env:
          COSIGN_EXPERIMENTAL: 1
      - name: Verify the pushed tags
        run: cosign verify ${{ env.REGISTRY }}/${{ github.repository }}/core:${{ env.RELEASE_VERSION }} --certificate-identity ${{ env.GH_URL }}/${{ github.repository }}/.github/workflows/core-release.yml@refs/tags/${{ env.RELEASE_VERSION }}  --certificate-oidc-issuer https://token.actions.githubusercontent.com
        env:
          COSIGN_EXPERIMENTAL: 1